/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Grafik.Editor;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAddWindow() {
        assertNotNull("App should have a Window Adder", App.addWindow());
    }
}
